FROM node:14-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

#Add files
COPY db.json /usr/src/app

# Install app dependencies
RUN npm install -g json-server 

EXPOSE 4000
CMD [ "node", "/usr/local/bin/json-server", "-p 4000", "db.json", "--host", "0.0.0.0"]
